Make benchmarks compile again
#128 broke the release build

```bash
☻  cargo build --release                                                                                                                                                                                                                                                                                                      9fe8280 ✗
   Compiling raw-ipa v0.1.0 (/Users/koshelev/workspace/raw-ipa)
error[E0277]: the trait bound `std::string::String: protocol::Step` is not satisfied
  --> src/protocol/modulus_conversion/convert_shares.rs:74:25
   |
74 |             (ctx.narrow(&format!("bit:{}", i)), b0, b1, input_xor_r)
   |                  ------ ^^^^^^^^^^^^^^^^^^^^^ the trait `protocol::Step` is not implemented for `std::string::String`
   |                  |
   |                  required by a bound introduced by this call
   |
   = help: the following other types implement trait `protocol::Step`:
             IpaProtocolStep
             ShuffleStep
             SortStep
             StreamingStep
             convert_shares::Step
note: required by a bound in `ProtocolContext::<'a, N>::narrow`
  --> src/protocol/context.rs:47:22
   |
47 |     pub fn narrow<S: Step>(&self, step: &S) -> Self {
   |                      ^^^^ required by this bound in `ProtocolContext::<'a, N>::narrow`
```

Modulus conversion uses strings as step and it is not allowed in release builds.

As temporary mitigation, I've enabled these conversions when test configuration is used. The proper fix would be to use steps that can be represented as strings for debug builds and as something else for release builds.